<x-app-layout>
    <x-slot name="header"><div><p class="eyebrow">{{ $materi->exists ? 'Edit materi' : 'Materi baru' }}</p><h1 class="mt-2 text-2xl font-extrabold text-white">{{ $materi->exists ? $materi->judul : $course->title }}</h1><p class="mt-1 text-sm text-slate-500">Susun konten, sumber belajar, dan opsi interaksi.</p></div></x-slot>
    <div class="shell py-8">
        <form method="POST" enctype="multipart/form-data" action="{{ $materi->exists ? route('materi.update', $materi) : route('materi.store', $course) }}" class="grid gap-6 lg:grid-cols-[1fr_340px]">
            @csrf @if($materi->exists) @method('PUT') @endif
            <section class="card space-y-6 p-6 sm:p-8">
                <div><label class="label" for="judul">Judul materi</label><input class="field" id="judul" name="judul" value="{{ old('judul',$materi->judul) }}" required placeholder="Contoh: Perjalanan makanan di tubuh"></div>
                <div><label class="label" for="ringkasan">Ringkasan singkat</label><textarea class="field" id="ringkasan" name="ringkasan" rows="3" maxlength="500" placeholder="Gambaran singkat yang muncul di daftar materi">{{ old('ringkasan',$materi->ringkasan) }}</textarea></div>
                <div><label class="label" for="deskripsi">Isi materi</label><textarea class="field min-h-[320px]" id="deskripsi" name="deskripsi" required placeholder="Tuliskan materi pembelajaran secara lengkap...">{{ old('deskripsi',$materi->deskripsi) }}</textarea><p class="mt-2 text-xs text-slate-500">Paragraf baru akan dipertahankan saat ditampilkan.</p></div>
                <div class="grid gap-5 sm:grid-cols-2"><div><label class="label" for="video_url">Tautan video</label><input class="field" id="video_url" type="url" name="video_url" value="{{ old('video_url',$materi->video_url) }}" placeholder="YouTube atau Google Drive"></div><div><label class="label" for="duration_minutes">Durasi (menit)</label><input class="field" id="duration_minutes" type="number" min="0" max="1440" name="duration_minutes" value="{{ old('duration_minutes',$materi->duration_minutes ?? 0) }}"></div></div>
                <div class="grid gap-5 sm:grid-cols-2"><div><label class="label" for="link_diskusi">Forum eksternal <span class="font-normal text-slate-500">(opsional)</span></label><input class="field" id="link_diskusi" type="url" name="link_diskusi" value="{{ old('link_diskusi',$materi->link_diskusi) }}" placeholder="Tautan Padlet"></div><div><label class="label" for="link_kuis">Kuis eksternal <span class="font-normal text-slate-500">(opsional)</span></label><input class="field" id="link_kuis" type="url" name="link_kuis" value="{{ old('link_kuis',$materi->link_kuis) }}" placeholder="Tautan Wordwall"></div></div>
            </section>
            <aside class="space-y-6">
                <section class="card p-6"><label class="label" for="thumbnail">Thumbnail materi</label><input class="field file:mr-4 file:rounded-lg file:border-0 file:bg-brand-400 file:px-3 file:py-2 file:text-xs file:font-bold file:text-ink" id="thumbnail" type="file" name="thumbnail" accept="image/*">@if($materi->thumbnail)<img src="{{ asset('storage/'.$materi->thumbnail) }}" class="mt-4 aspect-video w-full rounded-xl object-cover" alt="">@endif</section>
                <section class="card p-6"><label class="label" for="files">Modul & berkas</label><input class="field file:mr-4 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-xs file:font-bold file:text-white" id="files" type="file" name="files[]" multiple accept=".pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.zip"><p class="mt-2 text-xs leading-5 text-slate-500">Maks. 15 MB per berkas.</p>@if($materi->exists && $materi->files->isNotEmpty())<ul class="mt-3 space-y-1 text-xs text-slate-400">@foreach($materi->files as $file)<li class="truncate">• {{ $file->original_name }}</li>@endforeach</ul>@endif</section>
                <section class="card p-6"><label class="label" for="videos">Video lokal</label><input class="field file:mr-4 file:rounded-lg file:border-0 file:bg-white/10 file:px-3 file:py-2 file:text-xs file:font-bold file:text-white" id="videos" type="file" name="videos[]" multiple accept="video/*"><p class="mt-2 text-xs leading-5 text-slate-500">Gunakan bila tidak memakai tautan video.</p></section>
                <section class="card p-6"><label class="flex items-start gap-3"><input type="checkbox" name="is_published" value="1" class="mt-1 rounded border-white/20 bg-white/5 text-brand-400 focus:ring-brand-400" @checked(old('is_published',$materi->is_published))><span><strong class="block text-sm text-white">Terbitkan materi</strong><span class="mt-1 block text-xs leading-5 text-slate-500">Siswa dapat melihat materi setelah kelas juga diterbitkan.</span></span></label></section>
                <button class="btn-primary w-full" type="submit">{{ $materi->exists ? 'Simpan perubahan' : 'Tambahkan materi' }}</button><a href="{{ route('courses.show',$course) }}" class="btn-secondary w-full">Batalkan</a>
            </aside>
        </form>
    </div>
</x-app-layout>
