<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="eyebrow">Administrasi akun</p><h1 class="mt-2 text-2xl font-extrabold text-white">Pengguna Edutechia</h1><p class="mt-1 text-sm text-slate-500">Cari pengguna, lihat status verifikasi, dan atur akses akun.</p></div><a href="{{ route('admin.users.create') }}" class="btn-primary">+ Tambah guru</a></div></x-slot>
    <div class="shell py-8">
        <form method="GET" class="card flex flex-col gap-3 p-4 sm:flex-row"><input class="field mt-0 flex-1" name="search" value="{{ $search }}" placeholder="Cari nama atau email..."><select class="field mt-0 sm:w-48" name="role"><option value="">Semua role</option><option value="admin" @selected($role==='admin')>Admin</option><option value="teacher" @selected($role==='teacher')>Guru</option><option value="student" @selected($role==='student')>Siswa</option></select><button class="btn-primary" type="submit">Terapkan</button>@if($search||$role)<a href="{{ route('admin.users.index') }}" class="btn-secondary">Reset</a>@endif</form>
        <div class="card mt-6 overflow-x-auto"><table class="w-full min-w-[760px] text-left"><thead class="border-b border-white/5 bg-white/[0.025] text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Pengguna</th><th class="px-6 py-4">Role</th><th class="px-6 py-4">Verifikasi</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Terakhir masuk</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-white/5">
            @forelse($users as $user)<tr class="transition hover:bg-white/[0.02]"><td class="px-6 py-4"><div class="flex items-center gap-3"><span class="grid h-10 w-10 place-items-center rounded-xl bg-brand-400/10 font-bold text-brand-300">{{ mb_strtoupper(mb_substr($user->name,0,1)) }}</span><span><strong class="block text-sm text-white">{{ $user->name }}</strong><span class="text-xs text-slate-500">{{ $user->email }}</span></span></div></td><td class="px-6 py-4"><span class="badge capitalize">{{ $user->role }}</span></td><td class="px-6 py-4 text-sm {{ $user->email_verified_at ? 'text-emerald-300' : 'text-amber-300' }}">{{ $user->email_verified_at ? 'Terverifikasi' : 'Belum OTP' }}</td><td class="px-6 py-4"><span class="inline-flex items-center gap-2 text-sm"><span class="h-2 w-2 rounded-full {{ $user->status==='active' ? 'bg-emerald-400' : 'bg-red-400' }}"></span><span class="capitalize text-slate-300">{{ $user->status }}</span></span></td><td class="px-6 py-4 text-sm text-slate-500">{{ $user->last_login_at?->diffForHumans() ?? 'Belum pernah' }}</td><td class="px-6 py-4 text-right">@if($user->id!==auth()->id())<form method="POST" action="{{ route('admin.users.status',$user) }}">@csrf @method('PATCH')<button class="text-xs font-bold {{ $user->status==='active' ? 'text-red-300' : 'text-emerald-300' }}" type="submit">{{ $user->status==='active' ? 'Nonaktifkan' : 'Aktifkan' }}</button></form>@else<span class="text-xs text-slate-600">Akun Anda</span>@endif</td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-sm text-slate-500">Tidak ada pengguna yang cocok.</td></tr>@endforelse
        </tbody></table></div><div class="mt-8">{{ $users->links() }}</div>
    </div>
</x-app-layout>
