<x-app-layout>
    <x-slot name="header"><div><a href="{{ route('materi.show',$materi) }}" class="text-sm font-bold text-brand-400">← Kembali ke materi</a><h1 class="mt-2 text-2xl font-extrabold text-white">Forum: {{ $materi->judul }}</h1><p class="mt-1 text-sm text-slate-500">Tanyakan, bagikan pemahaman, dan hargai setiap perspektif.</p></div></x-slot>
    <div class="shell py-8">
        <div class="grid gap-7 lg:grid-cols-[1fr_300px]">
            <section>
                <form method="POST" action="{{ route('discussion.store',$materi) }}" class="card p-6">@csrf<label class="label" for="body">Mulai diskusi baru</label><textarea class="field" id="body" name="body" rows="4" required placeholder="Tulis pertanyaan atau refleksi Anda...">{{ old('body') }}</textarea><div class="mt-4 flex justify-end"><button class="btn-primary" type="submit">Kirim ke forum</button></div></form>
                @if($materi->link_diskusi && Str::contains($materi->link_diskusi,'padlet.com'))<details class="card mt-5 overflow-hidden"><summary class="cursor-pointer px-6 py-5 text-sm font-bold text-white">Tampilkan forum Padlet dari materi lama</summary><div class="border-t border-white/5 p-3"><iframe src="{{ $materi->link_diskusi }}" class="h-[608px] w-full rounded-xl bg-white" allow="camera;microphone;geolocation;display-capture;clipboard-write" title="Forum Padlet"></iframe></div></details>@endif
                <div class="mt-6 space-y-4">
                    @forelse($posts as $post)
                        <article x-data="{ reply: false }" class="card p-6"><div class="flex items-start gap-4"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-brand-400/10 font-bold text-brand-300">{{ mb_strtoupper(mb_substr($post->user->name,0,1)) }}</span><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h2 class="font-bold text-white">{{ $post->user->name }}</h2><span class="badge capitalize">{{ $post->user->role }}</span>@if($post->is_pinned)<span class="badge text-brand-300">Disematkan</span>@endif</div><p class="mt-1 text-xs text-slate-500">{{ $post->created_at->diffForHumans() }}</p><p class="mt-4 whitespace-pre-line text-sm leading-7 text-slate-300">{{ $post->body }}</p><div class="mt-4 flex items-center gap-4"><button @click="reply = !reply" type="button" class="text-xs font-bold text-brand-400">Balas</button>@if($post->user_id===auth()->id() || $canManage)<form method="POST" action="{{ route('discussion.destroy',$post) }}" onsubmit="return confirm('Hapus pesan ini?')">@csrf @method('DELETE')<button type="submit" class="text-xs font-bold text-red-300">Hapus</button></form>@endif</div></div></div>
                            <form x-cloak x-show="reply" method="POST" action="{{ route('discussion.store',$materi) }}" class="ml-14 mt-5 rounded-xl bg-white/[0.035] p-4">@csrf<input type="hidden" name="parent_id" value="{{ $post->id }}"><label class="sr-only" for="reply-{{ $post->id }}">Balasan</label><textarea class="field mt-0" id="reply-{{ $post->id }}" name="body" rows="3" required placeholder="Tulis balasan..."></textarea><div class="mt-3 flex justify-end"><button class="btn-primary px-4 py-2" type="submit">Kirim balasan</button></div></form>
                            @if($post->replies->isNotEmpty())<div class="ml-8 mt-6 space-y-3 border-l border-white/10 pl-5 sm:ml-14">@foreach($post->replies as $reply)<div class="rounded-xl bg-white/[0.03] p-4"><div class="flex items-center gap-2"><strong class="text-sm text-white">{{ $reply->user->name }}</strong><span class="text-xs text-slate-600">{{ $reply->created_at->diffForHumans() }}</span></div><p class="mt-2 whitespace-pre-line text-sm leading-6 text-slate-400">{{ $reply->body }}</p>@if($reply->user_id===auth()->id() || $canManage)<form class="mt-2" method="POST" action="{{ route('discussion.destroy',$reply) }}">@csrf @method('DELETE')<button class="text-xs font-bold text-red-300" type="submit">Hapus</button></form>@endif</div>@endforeach</div>@endif
                        </article>
                    @empty<div class="card p-10 text-center"><p class="font-bold text-white">Forum masih sunyi.</p><p class="mt-2 text-sm text-slate-500">Jadilah orang pertama yang memulai percakapan.</p></div>@endforelse
                </div>
                <div class="mt-8">{{ $posts->links() }}</div>
            </section>
            <aside class="space-y-5 lg:sticky lg:top-28 lg:self-start"><div class="card p-5"><p class="eyebrow">Etika diskusi</p><ul class="mt-4 space-y-3 text-sm leading-6 text-slate-500"><li>• Fokus pada topik materi.</li><li>• Sampaikan pendapat dengan sopan.</li><li>• Hindari membagikan data pribadi.</li><li>• Sertakan sumber bila mengutip.</li></ul></div>@if($materi->link_diskusi)<a href="{{ $materi->link_diskusi }}" target="_blank" class="block rounded-2xl border border-brand-400/20 bg-brand-400/10 p-5"><p class="text-sm font-bold text-white">Forum eksternal tersedia</p><p class="mt-2 text-xs leading-5 text-slate-500">Guru juga menyediakan ruang diskusi melalui layanan lain.</p><p class="mt-4 text-sm font-bold text-brand-400">Buka forum ↗</p></a>@endif</aside>
        </div>
    </div>
</x-app-layout>
