<x-app-layout>
    <x-slot name="header"><div><p class="eyebrow">{{ $course->exists ? 'Perbarui kelas' : 'Kelas baru' }}</p><h1 class="mt-2 text-2xl font-extrabold text-white">{{ $course->exists ? $course->title : 'Bangun ruang belajar baru' }}</h1></div></x-slot>
    <div class="shell py-8">
        <form method="POST" enctype="multipart/form-data" action="{{ $course->exists ? route('courses.update', $course) : route('courses.store') }}" class="grid gap-6 lg:grid-cols-[1fr_340px]">
            @csrf @if($course->exists) @method('PUT') @endif
            <section class="card space-y-6 p-6 sm:p-8">
                <div><label class="label" for="title">Nama kelas</label><input class="field" id="title" name="title" value="{{ old('title', $course->title) }}" required placeholder="Contoh: Memahami Sistem Pencernaan">@error('title')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
                <div><label class="label" for="description">Deskripsi kelas</label><textarea class="field" id="description" name="description" rows="8" required placeholder="Jelaskan tujuan, ruang lingkup, dan hasil belajar...">{{ old('description', $course->description) }}</textarea>@error('description')<p class="mt-2 text-sm text-red-300">{{ $message }}</p>@enderror</div>
                <div class="grid gap-5 sm:grid-cols-2"><div><label class="label" for="level">Tingkat</label><select class="field" id="level" name="level"><option @selected(old('level',$course->level)==='Umum')>Umum</option><option @selected(old('level',$course->level)==='Pemula')>Pemula</option><option @selected(old('level',$course->level)==='Menengah')>Menengah</option><option @selected(old('level',$course->level)==='Lanjutan')>Lanjutan</option></select></div>@if(auth()->user()->isAdmin())<div><label class="label" for="teacher_id">Guru pengampu</label><select class="field" id="teacher_id" name="teacher_id" required><option value="">Pilih guru</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((string)old('teacher_id',$course->teacher_id)===(string)$teacher->id)>{{ $teacher->name }}</option>@endforeach</select></div>@endif</div>
            </section>
            <aside class="space-y-6">
                <section class="card p-6"><label class="label" for="thumbnail">Sampul kelas</label><input class="field file:mr-4 file:rounded-lg file:border-0 file:bg-brand-400 file:px-3 file:py-2 file:text-xs file:font-bold file:text-ink" id="thumbnail" type="file" name="thumbnail" accept="image/*"><p class="mt-2 text-xs leading-5 text-slate-500">JPG/PNG/WebP, maksimal 3 MB. Rasio 16:9 disarankan.</p>@if($course->thumbnail)<img class="mt-4 aspect-video w-full rounded-xl object-cover" src="{{ asset('storage/'.$course->thumbnail) }}" alt="Sampul saat ini">@endif</section>
                <section class="card p-6"><p class="label">Pendaftaran siswa</p><div class="mt-4 space-y-3"><label class="flex cursor-pointer gap-3 rounded-xl border border-white/10 p-4"><input type="radio" name="is_open_enrollment" value="1" class="mt-1 text-brand-400 focus:ring-brand-400" @checked((bool)old('is_open_enrollment',$course->is_open_enrollment))><span><strong class="block text-sm text-white">Terbuka</strong><span class="mt-1 block text-xs leading-5 text-slate-500">Siswa dapat langsung bergabung.</span></span></label><label class="flex cursor-pointer gap-3 rounded-xl border border-white/10 p-4"><input type="radio" name="is_open_enrollment" value="0" class="mt-1 text-brand-400 focus:ring-brand-400" @checked(!(bool)old('is_open_enrollment',$course->is_open_enrollment))><span><strong class="block text-sm text-white">Dengan kode</strong><span class="mt-1 block text-xs leading-5 text-slate-500">Kode dibuat otomatis setelah disimpan.</span></span></label></div></section>
                <button type="submit" class="btn-primary w-full">{{ $course->exists ? 'Simpan perubahan' : 'Buat kelas' }}</button><a href="{{ $course->exists ? route('courses.show',$course) : route('dashboard') }}" class="btn-secondary w-full">Batalkan</a>
                @if($course->exists)<section class="rounded-2xl border border-red-400/20 bg-red-400/5 p-5"><p class="text-sm font-bold text-red-300">Zona berbahaya</p><p class="mt-2 text-xs leading-5 text-slate-500">Menghapus kelas juga menghapus materi, diskusi, kuis, dan progres.</p><button form="delete-course" type="submit" class="btn-danger mt-4 w-full">Hapus kelas</button></section>@endif
            </aside>
        </form>
        @if($course->exists)<form id="delete-course" method="POST" action="{{ route('courses.destroy',$course) }}" onsubmit="return confirm('Hapus kelas dan seluruh datanya?')">@csrf @method('DELETE')</form>@endif
    </div>
</x-app-layout>
